name: dt_ecosense
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - ld_impl_linux-aarch64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.14
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - antlr4-python3-runtime==4.9.3
      - decorator==5.1.1
      - easyocr==1.7.2
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - filelock==3.16.1
      - fsspec==2024.9.0
      - hydra-core==1.3.2
      - imageio==2.35.1
      - jinja2==3.1.4
      - lazy-loader==0.4
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.11.1.1
      - numpy==2.1.1
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - packaging==24.1
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.48
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyclipper==1.3.0.post5
      - pygments==2.18.0
      - python-bidi==0.6.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - scikit-image==0.24.0
      - scipy==1.14.1
      - shapely==2.0.6
      - six==1.16.0
      - sympy==1.13.3
      - tifffile==2024.9.20
      - torch==2.4.1
      - torchvision==0.19.1
      - tornado==6.4.1
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - wcwidth==0.2.13
